from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Protocol


class ComputerTools(Protocol):
    def control_music(self, action: str) -> bool: ...

    def play_music(self, query: str) -> bool: ...

    def search_web(self, query: str) -> bool: ...

    def list_files(self, location: str) -> list[str]: ...

    def find_file(self, query: str, location: str) -> Path | None: ...

    def open_file(self, query: str, location: str) -> Path | None: ...

    def create_folder(self, name: str, location: str) -> Path | None: ...

    def set_volume(self, level: int) -> bool: ...

    def create_reminder(self, title: str, due: datetime) -> bool: ...

    def create_calendar_event(
        self, title: str, start: datetime, end: datetime
    ) -> bool: ...
